print ("Speak the truth!")
print ("Speak it boldly, never fear;")
print ("Speak it so that all may hear;")
print ("In the end it shall appear")
print ("Truth is best in age and youth.")
print ("Speak the truth.")
print ("Chad Collard")
